import { Inter, Poppins } from 'next/font/google'
import '../../public/css/style.css'
import '../../public/css/responsive.css'
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css';
import Providers from '@/redux/store/Providers';
import PersistentDrawerLeft from '@/components/PersistentDrawerLeft';

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <PersistentDrawerLeft>
            {children}
          </PersistentDrawerLeft>
        </Providers>
      </body>
    </html>
  )
}
